export const SET_AUTH = 'SET_AUTH';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const TOGGLE_FAVORITE_TRACK = 'TOGGLE_FAVORITE_TRACK';
export const TOGGLE_FAVORITE_SHOW = 'TOGGLE_FAVORITE_SHOW';
export const TOGGLE_CHECKLIST_TRACK = 'TOGGLE_CHECKED_TRACK';
export const TOGGLE_CHECKLIST_SHOW = 'TOGGLE_CHECKED_SHOW';

export const TOGGLE_PLAYER = 'TOGGLE_PLAYER';
export const SET_PLAYER_WIDTH = 'SET_PLAYER_WIDTH';
export const SET_PLAYER_LAST_WIDTH = 'SET_PLAYER_LAST_WIDTH';

export const GET_FILTER_VALS_SUCCESS = 'GET_FILTER_VALS_SUCCESS';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_FULL_SHOW_SUCCESS = 'GET_FULL_SHOW_SUCCESS';

export const ADD_TRACKS = 'ADD_TRACKS';
export const REMOVE_TRACK = 'REMOVE_TRACK';
export const EMPTY_PLAYLIST = 'EMPTY_PLAYLIST';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
