export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT = 'LOGOUT';

export const CLOSE_PANE = 'CLOSE_PANE';
export const OPEN_PANE = 'OPEN_PANE';
export const RESIZE_PANES = 'RESIZE_PANES';

export const GET_FILTER_VALS_SUCCESS = 'GET_FILTER_VALS_SUCCESS';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_FULL_SHOW_SUCCESS = 'GET_FULL_SHOW_SUCCESS';
export const GET_TEASERS_SUCCESS = 'GET_TEASERS_SUCCESS';

export const ADD_TRACKS = 'ADD_TRACKS';
export const REMOVE_TRACK = 'REMOVE_TRACK';
export const EMPTY_PLAYLIST = 'EMPTY_PLAYLIST';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';

export const ADD_LIST = 'ADD_LIST';
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const RENAME_LIST = 'RENAME_LIST';
export const PUBLIC_LISTS = 'PUBLIC_LISTS';
export const INVALIDATE_PUBLIC = 'INVALIDATE_PUBLIC';
export const UPDATE_ACTIVE_LIST = 'UPDATE_ACTIVE_LIST';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
